---
- name: Adding Public Signing Key for Kubernetes
  apt-key:
    url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/Release.key
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add Kubernetes Repository
  apt_repository:
    repo: deb deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
    state: present
