---
- name: Join Workers
  vars:
    join_worker: "{{ lookup('file', '/tmp/kubeadm-join-worker.txt') }}" # lookup means to read the content of the file - run localhost by default
  shell: "{{ join_worker }}"