---
- name: Setting Up Cluster
  hosts: aws_ec2 # aws_ec2 seria todos os hosts
  become: true
  roles:
    - hostnames
    - dependency-packages
    - kube-packages
    - container-runtime
  # tasks:
  #   - name: Ping Control Plane
  #     ansible.builtin.ping:

---
- name: Init Cluster
  hosts: control_plane[0]
  become: true # become means to execute the tasks with elevated privileges (sudo)
  environment:
    KUBECONFIG: "{{ kube_config }}"
  roles:
    - init-cluster
    - container-network

---
- name: Join Control Plane
  hosts: control_planes:!control_plane[0]
  become: true
  roles:
    - join-control-planes

---
- name: Join Workers
  hosts: workers
  become: true
  roles:
    - join-workers

---
- name: Setting Up Cluster Auto Scaler
  hosts: control_plane[0]
  become: true # become means to execute the tasks with elevated privileges (sudo)
  environment:
    KUBECONFIG: "{{ kube_config }}"
  roles:
    - cluster-autoscaler